name: Build and Deploy ASP.NET Core Web API to Azure

on:
  push:
    branches:
      - master

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload published output
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download published output
      uses: actions/download-artifact@v3
      with:
        name: publish
        path: ./publish

    - name: Deploy to Azure Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: nscc-0475798-tickets-api
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
